---
#https://github.com/aquasecurity/trivy
- name: "Install Script trivy"
  shell: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

- name: "Scan elasticsearch_image"
  shell: trivy image "{{ elasticsearch_image }}"

- name: "Scan kibana_image"
  shell: trivy image "{{ kibana_image }}"

- name: "Scan logstash_image"
  shell: trivy image "{{ logstash_image }}"

- name: "Scan heartbeat_image"
  shell: trivy image "{{ heartbeat_image }}"

- name: "Scan metricbeat_image"
  shell: trivy image "{{ metricbeat_image }}"

- name: "Scan filebeat_image"
  shell: trivy image "{{ filebeat_image }}"

- name: "Scan heartbeatwatcher_image"
  shell: trivy image "{{ heartbeatwatcher_image }}"


#https://github.com/quay/clair

- name: Deploy container clair-db
  docker_container:
    name: "clair_db"
    hostname: "clair_db"
    image: "arminc/clair-db:2017-09-18"
    ports:
      - "5432:5432"

- name: Deploy container clair-local-scan
  docker_container:
    name: "clair"
    hostname: "clair"
    state: "started"
    restart_policy: "always"
    image: "arminc/clair-local-scan:v2.0.6"
    ports:
      - "6060:6060"
    links:
      - "clair_db:postgres"
  register: clair_service

- name: Get clair container IP
  set_fact:
    container_ip: "{{ clair_service.ansible_facts.docker_container.NetworkSettings.IPAddress }}"

- name: Check container container clair-local-scan is running
  wait_for:
    host: "{{ container_ip }}"
    port: 6060

- name: Downloading and setting up clair-scanner binary
  get_url:
    url: https://github.com/arminc/clair-scanner/releases/download/v6/clair-scanner_linux_amd64
    dest: /usr/local/bin/clair-scanner
    mode: 0755