---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

######################filebeat
    - name: "Install Filebeat using Apt  Python 3.7 on focal"
      dist: focal
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        # add Elastic’s signing key so that the downloaded package can be verified
        - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        # add the repository
        - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list  
        # update repository and install Filebeat
        # Configure Filebeat using a YAML configuration file
        # on Docker,  /etc/filebeat/filebeat.yml
        - sudo apt-get update -qq && sudo apt-get install -qqy filebeat        
      after_success:
        - deactivate

    - name: "Install Filebeat using Apt  Python 3.7 on bionic"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        # add Elastic’s signing key so that the downloaded package can be verified
        - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        # add the repository
        - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list  
        # update repository and install Filebeat
        # Configure Filebeat using a YAML configuration file
        # on Docker,  /etc/filebeat/filebeat.yml
        - sudo apt-get update -qq && sudo apt-get install -qqy filebeat        
      after_success:
        - deactivate

    - name: "Install Filebeat on Docker Python 3.7 on focal"
      dist: focal
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        # install Filebeat as a container on your host 
        # and configure it to collect container logs or log files from your host
        # Configure Filebeat using a YAML configuration file
        # on Docker,  /usr/share/filebeat/filebeat.yml
        # - docker pull docker.elastic.co/beats/filebeat7.4.2 #Error response from daemon: manifest for docker.elastic.co/beats/filebeat7.4.2:latest not found: manifest unknown: manifest unknown
        - docker image ls
      after_success:
        - deactivate
######################metricbeat 
    - name: "Install Metricbeat on Linux using Apt  Python 3.7 on focal"
      dist: bionic
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
      # add Elastic’s signing key so that the downloaded package can be verified
        - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
        # add the repository
        - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
        # update repositories and install Metricbeat
        - sudo apt-get update -qq && sudo apt-get install -qqy metricbeat
      after_success:
        - deactivate

    - name: "Install Metricbeat on Docker  Python 3.7 on bionic"
      dist: bionic
      services: docker 
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
      # pull Elastic’s Metricbeat image
        - docker pull docker.elastic.co/beats/metricbeat:7.4.2
      after_success:
        - deactivate

    - name: "Install Metricbeat on Kubernetes  Python 3.7 on bionic"
      dist: bionic
      services: docker 
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
      # deploy a Docker image of Metricbeat on Kubernetes
        - curl -L -O https://raw.githubusercontent.com/elastic/beats/7.6/deploy/kubernetes/metricbeat-kubernetes.yaml
      after_success:
        - deactivate