---
sudo: required
dist: bionic
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

    - name: "Install ELK Metricbeat OSS wo homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      # Installing Homebrew
      - cd /usr/local
      - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      # Brew Install Elasticsearch
      - brew tap elastic/tap
      # - brew install elastic/tap/elasticsearch-full
      - brew install elastic/tap/elasticsearch-oss
      # - brew install elasticsearch
      # run Elasticsearch
      - brew services start elastic/tap/elasticsearch-oss
      # OR don’t want/need a background service just run
      # - elasticsearch
      # - curl http://localhost:9200 #curl: (7) Failed to connect to localhost port 9200: Connection refused
      # Installing Kibana with Homebrew
      - brew install elastic/tap/kibana-oss
      # If you wish to preserve your plugins upon upgrade, 
      # make a copy of /usr/local/opt/kibana-full/plugins before upgrading, 
      # and copy it into the new keg location after upgrading
      # run Kibana in the background
      - brew services start elastic/tap/kibana-oss
      # OR don’t want/need a background service just run
      # - kibana
      # access Kibana
      # - curl http://localhost:5601
      # System Metrics Pipeline from Local Machine to Kibana
      - brew install elastic/tap/metricbeat-oss
      # run Kibana in the background
      - brew services start elastic/tap/metricbeat-oss
      # OR don’t want/need a background service just run
      # - metricbeat
      # verify by listing Elasticsearch indices
      - curl -X GET "localhost:9200/_cat/indices?v" 
      after_success:
        - deactivate

    - name: "Install ELK Metricbeat wo homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      # Installing Homebrew
      - cd /usr/local
      - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      # Brew Install Elasticsearch
      - brew tap elastic/tap
      - brew install elastic/tap/elasticsearch-full
      # - brew install elastic/tap/elasticsearch-oss
      # - brew install elasticsearch
      # run Elasticsearch
      - brew services start elastic/tap/elasticsearch-full
      # OR don’t want/need a background service just run
      # - elasticsearch
      # - curl http://localhost:9200 #curl: (7) Failed to connect to localhost port 9200: Connection refused
      # Installing Kibana with Homebrew
      - brew install elastic/tap/kibana-full
      # If you wish to preserve your plugins upon upgrade, 
      # make a copy of /usr/local/opt/kibana-full/plugins before upgrading, 
      # and copy it into the new keg location after upgrading
      # run Kibana in the background
      - brew services start elastic/tap/kibana-full
      # OR don’t want/need a background service just run
      # - kibana
      # access Kibana
      # - curl http://localhost:5601
      # System Metrics Pipeline from Local Machine to Kibana
      - brew install elastic/tap/metricbeat-full
      # run Kibana in the background
      - brew services start elastic/tap/metricbeat-full
      # OR don’t want/need a background service just run
      # - metricbeat
      # verify by listing Elasticsearch indices
      - curl -X GET "localhost:9200/_cat/indices?v" 
      after_success:
        - deactivate

    - name: "Install ELK Metricbeat OSS w homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          # casks:
          # https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
          # - wkhtmltopdf
          taps: elastic/tap 
          packages:
          - elasticsearch-oss 
          - kibana-oss
          - metricbeat-oss
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      # run Elasticsearch
      - brew services start elastic/tap/elasticsearch-full
      # OR run Elasticsearch
      # - elasticsearch
      # - curl http://localhost:9200 #curl: (7) Failed to connect to localhost port 9200: Connection refused
     # If you wish to preserve your plugins upon upgrade, 
      # make a copy of /usr/local/opt/kibana-full/plugins before upgrading, 
      # and copy it into the new keg location after upgrading
      # run Kibana in the background
      - brew services start elastic/tap/kibana-full
      # OR don’t want/need a background service just run
      # - kibana 
      # access Kibana
      # - curl http://localhost:5601 #curl: (7) Failed to connect to localhost port 9200: Connection refused
      # System Metrics Pipeline from Local Machine to Kibana
      # run Kibana in the background
      - brew services start elastic/tap/metricbeat-full
      # OR don’t want/need a background service just run
      # - metricbeat
      # verify by listing Elasticsearch indices
      # - curl -X GET "localhost:9200/_cat/indices?v" #curl: (7) Failed to connect to localhost port 9200: Connection refused          
      after_success:
        - deactivate

    - name: "Install ELK Metricbeat w homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          # casks:
          # https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
          # - wkhtmltopdf
          taps: elastic/tap 
          packages:
          - elasticsearch-full  
          - kibana-full 
          - metricbeat-full        
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
      # run Elasticsearch
      - brew services start elastic/tap/elasticsearch-full
      # OR run Elasticsearch
      # - elasticsearch
      # - curl http://localhost:9200 #curl: (7) Failed to connect to localhost port 9200: Connection refused
     # If you wish to preserve your plugins upon upgrade, 
      # make a copy of /usr/local/opt/kibana-full/plugins before upgrading, 
      # and copy it into the new keg location after upgrading
      # run Kibana in the background
      - brew services start elastic/tap/kibana-full
      # OR don’t want/need a background service just run
      # - kibana 
      # access Kibana
      # - curl http://localhost:5601 #curl: (7) Failed to connect to localhost port 9200: Connection refused
      # System Metrics Pipeline from Local Machine to Kibana
      # run Kibana in the background
      - brew services start elastic/tap/metricbeat-full
      # OR don’t want/need a background service just run
      # - metricbeat
      # verify by listing Elasticsearch indices
      # - curl -X GET "localhost:9200/_cat/indices?v" #curl: (7) Failed to connect to localhost port 9200: Connection refused          
      after_success:
        - deactivate

    - name: "Install Filebeat w homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          taps: elastic/tap
          packages:
          - filebeat-oss # install the -oss version            
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        # Configure Filebeat using a YAML configuration file
        # /usr/local/etc/filebeat/filebeat.yml
        # /usr/local/cellar/filebeat-full/filebeat.yml.
      - java -version 
      after_success:
        - deactivate

    - name: "Install Filebeat wo homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        # Configure Filebeat using a YAML configuration file
        # /usr/local/etc/filebeat/filebeat.yml
        # /usr/local/cellar/filebeat-full/filebeat.yml.
      # - brew install elastic/tap/filebeat-full 
      - brew install elastic/tap/filebeat-oss # install the -oss version
      # - brew install filebeat # install the -oss version      
      after_success:
        - deactivate

    - name: "Install Metricbeat w homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      addons:
        homebrew:
          # casks:
          # https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
          # - wkhtmltopdf
          taps: elastic/tap
          packages:
          - metricbeat-oss  # install the -oss version         
          update: true
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        # Configure Filebeat using a YAML configuration file
        # /usr/local/etc/filebeat/filebeat.yml
        # /usr/local/cellar/filebeat-full/filebeat.yml.
      - java -version 
      after_success:
        - deactivate

    - name: "Install Metricbeat wo homebrew on macOS 10.15.7 osx xcode12.2"
      os: osx
      osx_image:
        - xcode12.2 #macOS 10.15.7
      language: shell
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        # Configure Filebeat using a YAML configuration file
        # /usr/local/etc/filebeat/filebeat.yml
        # /usr/local/cellar/filebeat-full/filebeat.yml.
      # - brew install elastic/tap/metricbeat-full
      - brew install elastic/tap/metricbeat-oss # install the -oss version
      # - brew install metricbeat # install the -oss version
      after_success:
        - deactivate        