---

- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"


# - name: Update repositories as a separate step
#   apk:
#     update_cache: yes
# - name: Load a variable file based on the OS type, or a default if not found.
#   include_vars: "{{ item }}"
#   with_first_found:
#     - "{{ ansible_distribution }}.yml"
#     - "{{ ansible_os_family }}.yml"
#     - default.yaml
#     # - ansible_facts['distribution_major_version'] == "3.8"
# - name: Install system packages
#   package:
#     name: '{{ system_packages }}'
#     use: '{{ ansible_pkg_mgr }}'
#     state: present


- name: "Add Debian docker"
  include_tasks: docker_debian.yml
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

- name: "Add RedHat docker"
  include_tasks: docker_redhat.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS','Scientific'] "

- name: "Add Fedora docker"
  include_tasks: docker_fedora.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['Fedora'] "
