---

- name: Install Docker SDK for Python
  pip:
    name: "docker<5" 

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started

- name: Create docker network
  docker_network:
    name: "{{ network_name }}"