# - name: Restart nginx container
#   docker_container:
#     name: ng01
#     restart: true

- name: Restart Logstash
  service: 
    name: logstash 
    state: restarted
    enabled: yes
  ignore_errors: true