---

- name: "Deploy docker-ce"
  gather_facts: true
  hosts:  vg-docker-01
  become: yes
  vars:
    # ansible_python_interpreter: /bin/python3
    #Changed password for user kibana
    vault_kibana_password: H9H9YOuu75SwFYKSTIVJ
    #Changed password for user elastic
    vault_elastic_password: oOYUXhSg2DcImWEsPpR5
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
    - docker
    - docker-init
    - clean
    - elasticsearch
    - kibana
    - logstash
    # - heartbeat
    - filebeat
    # - metricbeat
    - nginx
    # - heartbeat-watcher