---
#
# Installing Jenkins
#

- name: Update apt cache.
  apt: update_cache=true cache_valid_time=600

- name: Ensure depencidencies
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
      - openjdk-8-jre
      # - default-jre
    state: present

- name: "add Jenkins repository key to the system"
  apt_key:
    url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
    state: present
       
- name: "Add Jenkins repo"
  shell:
    cmd: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'



- name: Update repositories cache and install update package
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins
  systemd:
    name: jenkins
    state: started
    enabled: true
    
- name: Sleep 30 seconds 
  wait_for: timeout=30

    

- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: adminpassword

- name: Print init password Jenkins
  debug:
    var: adminpassword.stdout
