---
#
# Installing Jenkins
#

- name: add jenkins key
  apt_key:
    state: present
    url: "{{ jenkins_key_rpmU }}"

- name: "Set EPEL yum repository"
  apt_repository:
      filename: "{{ item.value.name }}"
      repo: "{{ item.value.url }}"
      description: "{{ item.value.description }}"
  loop:
      "{{ lookup('dict',reposU) }}"    

- name: "Install Java and Jenkins"
  apt:
      name: "{{ item.value.name }}" 
      state: present
  loop:
      "{{ lookup('dict',softwaresU) }}"

- name: "Starting jenkins"
  service:
      name: "jenkins"
      state: started
      enabled: yes