name: "docker compose ELK workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 * * 0' #At 00:00 on Sunday every week

jobs:



  ubuntu-1804-virtualenv-job:
    name: "ubuntu-18.04 jenkins virtualenv job"
    runs-on: ubuntu-18.04
    env:
      COMPOSE_FILE: "${{ github.workspace }}/dockercomposefiles/docker-compose-elk.yml"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "python3 virtualenv"
      run: |
        pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt 
        virtualenv --version
        # docker-compose -f ~/dockercomposefiles/docker-compose-elk.yml up
        pip list
        deactivate
    - name: "docker compose elk"
      run: |
        ls -lai
        # .FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/dockercomposefiles/docker-compose-elk.yml'
        # docker-compose -f ~/dockercomposefiles/docker-compose-elk.yml up
        stat dockercomposefiles/docker-compose-elk.yml
        # .FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/dockercomposefiles/docker-compose-elk.yml'
        # docker-compose -f ~/dockercomposefiles/docker-compose-elk.yml up
        # build path /home/runner/work/ELK-sandbox/ELK-sandbox/dockercomposefiles/elasticsearch either does not exist, is not accessible, or is not a valid URL.
        docker-compose -f ${COMPOSE_FILE} up