name: "Ubuntu dockerized ELK workflow"


on:
  push:
    branches: [ test ]
  # schedule:
  #     - cron:  '0 0 * * 0' #At 00:00 on Sunday every week

jobs:

  ubuntu-1604-virtualenv-job:
    name: "ubuntu-16.04 jenkins virtualenv job"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    # - name: "python2 virtualenv"
    #   run: |
    #     pip install virtualenv
    #     virtualenv -p $(which python3) ~venvpy3
    #     source ~venvpy3/bin/activate
    #     pip install -r requirements.txt 
    #     virtualenv --version
    #     pip list
    #     deactivate

  ubuntu-1804-virtualenv-job:
    name: "ubuntu-18.04 jenkins virtualenv job"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "python3 virtualenv"
      run: |
        pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt 
        virtualenv --version
        pip list
        deactivate

  ubuntu-2004-virtualenv-job:
    name: "ubuntu-20.04 jenkins virtualenv job"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "python3 virtualenv"
      run: |
        pip3 install virtualenv
        virtualenv -p $(which python3) ~venvpy3
        source ~venvpy3/bin/activate
        pip install -r requirements.txt 
        virtualenv --version
        git clone https://github.com/deviantony/docker-elk.git
        cd /docker-elk
        docker-compose up -d
        docker ps
        curl http://localhost:9200/_security/_authenticate
        {
          "name" : "VO32TCU",
          "cluster_name" : "docker-cluster",
          "cluster_uuid" : "pFgIXMErShCm1R1cd3JgTg",
          "version" : {
            "number" : "6.1.0",
            "build_hash" : "c0c1ba0",
            "build_date" : "2017-12-12T12:32:54.550Z",
            "build_snapshot" : false,
            "lucene_version" : "7.1.0",
            "minimum_wire_compatibility_version" : "5.6.0",
            "minimum_index_compatibility_version" : "5.0.0"
          },
          "tagline" : "You Know, for Search"
        }
        curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.1.2-darwin-x86_64.tar.gz
        tar xzvf metricbeat-6.1.2-darwin-x86_64.tar.gz
        cd metricbeat-6.1.2-darwin-x86_64
        sudo cat metricbeat.yml
        sudo chown root metricbeat.yml 
        sudo chown root modules.d/system.yml 
        # sudo ./metricbeat -e -c metricbeat.yml -d "publish"
        curl -XGET 'localhost:9200/_cat/indices?v&pretty'
    - name: "deactivate virtualenv"
      run: hostnamectl status   